 trigger:
- main
 
pool:
  name: Default
  demands:
- agent.name == myagent1
 
steps:
- script: |
    # Update the package list
    sudo apt-get update
    
    # Install prerequisites
    sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
    
    # Add Docker’s official GPG key
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    
    # Add Docker repository
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    
    # Update the package list again
    sudo apt-get update
    
    # Install Docker
    sudo apt-get install -y docker-ce
    
    # Start and enable Docker service
    sudo systemctl start docker
    sudo systemctl enable docker
    
    # Verify Docker installation
    docker --version
  displayName: 'Install Docker'
